language: node_js
script: npm test
node_js:
  - "4.1"
  - "5.7.0"
  - "0.10"
  notifications:
    email: 
        recipients:
            - stefan@clevernudge.com
        on_success: never
        on_failure: always
